# Generated by Django 6.0.5 on 2026-10-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('disponible', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=100)),
                ('volumen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CategoriasApp.volumen')),
            ],
        ),
    ]
